### ISSUE TITLE
Represent time stamps as integer ratios?

### ISSUE THREAD

**Issue by simonster** [NeurodataWithoutBorders/specification#2]
I'm not sure I like the choice of a Float64 array for timestamps. While floating point is easier to deal with in some circumstances, in nearly all cases, timestamps will not be exactly representable as floating point numbers.

Consider data acquired at 1000 Hz with a timestamp for every sample. The first timestamp is 0, the second is `0.001`, the tenth is `0.009`, and the eleventh is `0.01`. Unfortunately, in floating point arithmetic, it is not the case that `0.001 - 0 == 0.01 - 0.009`. Instead, `(0.001 - 0) - (0.01 - 0.009) = -8.673617379884035e-19`. If stored as floating point numbers, timestamps become unequally spaced even when they represent equally spaced times.

All the electrophysiology equipment I know gives timestamps in terms of the number of cycles of a system clock, so they could be exactly represented as the ratio of an integer representing the individual time stamp and the integer clock frequency, which is fixed across all time stamps.

Similarly, depending on the recording equipment, the sampling rate may not be exactly representable as a floating point number, and this is likely to be the case if it isn't an integer, although I'd be surprised if it were irrational.

Please let me know if there is a better place to continue this discussion than in this repository.

**Comment by keithg-alleninstitute** [comment]
Hi Simon,

Thank you for your ideas. There is presently no place dedicated to discussions like this, but having one would certainly be useful.

You raise good points regarding integral representation of time and there was a lot of discussion about this. Some factors that went into the decision to use float64 are below. It's not an optimal solution but it seemed the most workable place to start.

Best wishes,

Keith

---

1) Float64 represents time to a higher precision than the margin of error in most recording/tracking/stimulus hardware, so little if any information is lost due inexact representation. Hardware clocks also drift over time so integral 'tick' values only represent approximate times

2) On many hardware sources, the reported sample time is based on the system clock but individual samples are skewed relative to this clock. For example, imagine an electrophys rig with 16 electrodes recording at 25KHz. Each electrode is often physically sampled at slightly different times and then reported together on the same 25KHz tick. Some people correct for this sub-clock-resolution skew. Using floating point allows for that more easily

3) Integral values are indeed much easier to use coming from a particular piece of recording hardware. The issue gets more difficult when information from multiple hardware sources is combined, such as recording device(s), stimulus device(s), tracking video(s) and/or other DAQ hardware, each with an independent clock. The timestamps recorded on the different devices must be adjusted to a common timeframe before analysis, and in most cases these cannot be adjusted to accurately match the integral values on any of the individual clock sources

4) An alternative would be for each person to store time data in whatever unit they desired and to require a user to multiply a scaling factor to get to a common time unit. Given points 1-3, use of integral tick values seems more of an edge case (e.g., streaming data from a single piece of hardware). The field 'starting_time' (instead of 'timestamps') can be used as an alternative for many of those cases, as it stores the rate information (e.g., 25KHz) and the time of the first sample. Subsequent samples are calculated based on this information

5) Using a standard time unit is arguably easier and reduces the opportunity for errors when interpreting timestamps. The flip side is that floating point makes comparisons of equality difficult (e.g., "if t0 == t1 then..." won't often work if computations are involved), as you point out.
